### ISSUE TITLE
Add parameter button is broken when URL is not set

### ISSUE THREAD

**Issue by thureos** [treagod/spectator#10]
First of all, thank you very much for this initiative, I was going to do the same thing but you guys are way far away from what I have (almost nothing).

I downloaded spectator and tried to add a parameter Parameters > Add parameter and the app closed. This is the log:
`com.github.treagod.spectator 
(com.github.treagod.spectator:31164): libsoup-CRITICAL **: 14:03:48.148: soup_uri_set_query: assertion 'uri != NULL' failed
(com.github.treagod.spectator:31164): libsoup-CRITICAL **: 14:03:48.148: soup_uri_to_string_internal: assertion 'uri != NULL' failed
** (com.github.treagod.spectator:31164): CRITICAL **: 14:03:48.148: spectator_widgets_sidebar_item_escape_url: assertion 'url != NULL' failed
Segmentation fault
`

Cheers.

**Comment by treagod** [comment]
I'm glad you like this project.

I'll look into this issue later this day

**Comment by treagod** [comment]
The last update in AppCenter should have solved that problem.

Please let me know if everything works and then close this issue

**Comment by thureos** [comment]
I can confirm that the issue is gone, thank you so much. I also purchase the app ; ).
