### ISSUE TITLE
Display chunked data in response of POST request

### ISSUE THREAD

**Issue by mtrenkmann** [treagod/spectator#17]
Not sure whether I am doing something wrong, but it seems that the app currently does not display the response body of a POST request. According to the HTTP standard, it is allowed that POST requests send back body data.

PS: I am an elementary OS user and willing to pay for that feature via AppCenter.

Thank you for developing this native app.

**Comment by treagod** [comment]
First of all, I'm really glad that you like this project.

Does a response view appear like in this picture?
![Screenshot from 2019-03-24 14 08 18](https://user-images.githubusercontent.com/4701538/54879930-696a6f80-4e3f-11e9-80f3-920ff071a3f3.png)

If so, is it filled with anything? If nothing happens, try to open Spectator from terminal with `com.github.treagod.spectator`, repeat your steps and tell me if any error is printed out

**Comment by mtrenkmann** [comment]
I use the AppCenter version (0.2.0).

After some testing, I can confirm that the POST response body is displayed when it contains JSON data. However, in my case it is plain text with the content type `text/tab-separated-values; charset=utf-8`. In addition, it makes use of `Transfer-Encoding: chunked`.

The actual response is

```
Server: nginx
Date: Sun, 24 Mar 2019 09:48:04 GMT
Content-Type: text/tab-separated-values; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *

OK	3
Hello_0	2144437	491159	1643	2009	1103806606387	0.710857
hello_0	829912	349504	1584	2009	1103806616901	0.275107
HELLO_0	42343	17176	1802	2009	1103806726346	0.0140362
OK	12
world_0	143517023	2972564	1500	2009	1103806595256	0.780836
World_0	38886149	2169968	1507	2009	1103806595852	0.211569
WORLD_0	1390837	422485	1584	2009	1103806610474	0.00756715
WOrld_0	1569	1356	1805	2009	1103807584731	8.53649e-06
WoRLD_0	855	482	1827	2009	1103808055077	4.65182e-06
wOrld_0	579	484	1801	2009	1103808457421	3.15018e-06
worLd_0	541	291	1801	2009	1103808535838	2.94343e-06
WorLd_0	448	210	1838	2009	1103808766000	2.43744e-06
WORlD_0	399	278	1822	2009	1103808916064	2.17085e-06
wORLD_0	303	164	1809	2009	1103809291205	1.64854e-06
woRLD_0	279	173	1827	2009	1103809405215	1.51796e-06
WORLd_0	227	141	1831	2009	1103809685038	1.23504e-06
```

Spectator's console output is

```
Unable to parse the string: <data>:1:2: Parse error: unexpected identifier `OK', expected value
Error parsing JSON.
```

**Comment by treagod** [comment]
Alright, thanks for the input. I think I know what’s wrong. I will try to fix it ASAP

**Comment by treagod** [comment]
I’ve committed a hotfix for this issues. The design is not optimal yet, but will be tackled with version 0.3.

Please tell me if the hotfix solves your issue when it lands in AppCenter

**Comment by mtrenkmann** [comment]
Received and installed the update today. Works like a charm. Purchased. Thank you!

Please keep up the good work. This is a really good alternative to all these bloated non-native apps out there. Some improvements I would like to see:

- Text showing request/response payloads rendered in monospace font.
- Read-only response payload (at the moment I can edit it).
- Auto-formatting of JSON would be nice.

**Comment by treagod** [comment]
Thank you very much! Exactly this kind of feedback is why I already released the app, even though many of my goals are not implemented yet.

I will put these suggestions on my todo-list. But what do you mean with 

> Auto-formatting of JSON would be nice.

In the JSON view there is a dropdown item 'Prettified'. Or do you mean the JSON editor in the request view?

**Comment by mtrenkmann** [comment]
Yeah, I mean the request view. And thinking about it, auto-formatting could be kind of annoying. But, there could be a "Prettify" button at least. Cheers!
