### ISSUE TITLE
Error notification stays open after successful request

### ISSUE THREAD

**Issue by xpaulnim** [treagod/spectator#19]
If I make a request with a wrong URL, then fix the issue and make the request again, I expect the red error notification to go away.
![Capture](https://user-images.githubusercontent.com/8648705/55960561-f6e1f800-5c64-11e9-9278-c1422fc1cd87.png)

**Comment by treagod** [comment]
Oh yeah, that would make sense. I’m going to implement it as soon as I have time for it.

**Comment by treagod** [comment]
The new release 0.3.0 should fix this problem. Can you please give me feedback after it is rolled out?

**Comment by xpaulnim** [comment]
It works great thank you @treagod
