### ISSUE TITLE
[Bug] Charset

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#20]
Please, Could you use UTF-8 charset like default?

Look the bug in **Category** field in the SS.

![Captura de tela de 2019-05-26 21-49-56](https://user-images.githubusercontent.com/11943860/58389363-5111ff00-8000-11e9-8e24-6334c456e3ef.png)

**Comment by treagod** [comment]
Thanks for the feedback. I will look into it as soon as possible.

**Comment by btd1337** [comment]
@treagod please, Could you to accept the PR: https://github.com/treagod/spectator/pull/21

**Comment by treagod** [comment]
Hi, sorry for the long wait.

I checked the problem, but can't reproduce it. Is there a chance that the server can't handle it?

![utf8_works](https://user-images.githubusercontent.com/4701538/61813997-55636880-ae47-11e9-9380-c15cd12fbf69.png)

**Comment by btd1337** [comment]
The problem doesn't reproduce in other Rest Clients, for example Insomnia. 

An observation: Your test must contain *Latin characters*.

Test Endpoint: https://lancheteria-api.herokuapp.com/restaurants

**Insomnia**

![Captura de tela de 2019-07-27 00-17-22](https://user-images.githubusercontent.com/11943860/61989326-1b8b9100-b004-11e9-8ad6-444154498424.png)

![Captura de tela de 2019-07-27 00-17-42](https://user-images.githubusercontent.com/11943860/61989328-25ad8f80-b004-11e9-819a-4dc7f47a6521.png)


**Spectator**

![Captura de tela de 2019-07-27 00-18-01](https://user-images.githubusercontent.com/11943860/61989329-3231e800-b004-11e9-9340-26eceb7632c7.png)

![Captura de tela de 2019-07-27 00-18-19](https://user-images.githubusercontent.com/11943860/61989331-378f3280-b004-11e9-84d0-52e0bb62ac4a.png)

**Comment by btd1337** [comment]
![Captura de tela de 2019-07-27 00-33-56](https://user-images.githubusercontent.com/11943860/61989472-437bf400-b006-11e9-8c48-df63694443f3.png)

**Comment by treagod** [comment]
Thanks for providing the example. The revision ae03bf6 should fix it.
