### ISSUE TITLE
Folders to group requests

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#25]
Would it be possible to create folders to group requests?

Look like how it is done in Insomnia App:

![Captura de tela de 2019-06-07 14-55-25](https://user-images.githubusercontent.com/11943860/59123798-75d97100-8934-11e9-8827-3e0b95de5c18.png)

**Comment by treagod** [comment]
Actually that's in work right now. If you want to have a look at it, there's a branch *grouping* where I'm working on it

**Comment by btd1337** [comment]
Great news!

I'll wait these changes come to production branch :)

**Comment by btd1337** [comment]
@treagod Any things more is needed?

**Comment by treagod** [comment]
Not for now. I submitted Spectator 0.4.0 with the current state of collections. This will cover this feature request. If you're satisfied with the collections so far, you can close this ticket.

Not to say there is nothing to be done for the collections (in fact there is a lot to be done) but I hope the next release will show the concept just fine

**Comment by btd1337** [comment]
Great!

So, Was the item **[ ]Create collections of requests** in the README finished?

**Comment by treagod** [comment]
Yep, done
