### ISSUE TITLE
Sidebar Resizable

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#28]
Please, It consider the Collection sidebar width resizable. When endpoints characters growth the auto width growth much too.

![Captura de tela de 2019-07-27 00-35-06](https://user-images.githubusercontent.com/11943860/61989515-ed5b8080-b006-11e9-879a-27c6f6eae77c.png)

![Captura de tela de 2019-07-27 00-39-12](https://user-images.githubusercontent.com/11943860/61989521-fba99c80-b006-11e9-97a5-d09dfe76b204.png)

**Comment by treagod** [comment]
[This commit](https://github.com/treagod/spectator/commit/897c2e9ae58c87fe9fc3f0a9102d434b0e1ee57c) improves the sidebar behavior
