### ISSUE TITLE
Feature Request: Reorder Requests

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#29]
Make Spectator able to reorder request and collection list.

![Captura de tela de 2019-07-29 18-29-28](https://user-images.githubusercontent.com/11943860/62084118-d7300900-b22e-11e9-97d8-ac742d6e9b97.png)

**Comment by treagod** [comment]
Yes, this feature is on my list. I plan it for the next release (I aim for 1.0, so it might take a little, but please tell me how urgent on a scale 0-10 you would rate this feature)

**Comment by btd1337** [comment]
Great!

So, Was the item *Create collections of requests* in the README finished?

**Comment by btd1337** [comment]
I think that the next resource in the list is more important:

- [ ] Create request enviroments

But, maybe a value 7 in the rating.

**Comment by btd1337** [comment]
@treagod Please, look at this:

https://blog.gtk.org/2017/04/23/drag-and-drop-in-lists/

https://blog.gtk.org/2017/06/01/drag-and-drop-in-lists-revisited/

**Comment by treagod** [comment]
[Closed by this PR](https://github.com/treagod/spectator/pull/44)
