### ISSUE TITLE
Publish Spectator on Flathub

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#30]
It would be great if your app were published to the [Flathubs app store](https://flathub.org/home).

In [this link](https://github.com/flathub/flathub/wiki/App-Submission) is the App Submission Tutorial and in the [other link](https://github.com/flathub?utf8=%E2%9C%93&q=+com.github.&type=&language=) are some examples.

**Comment by btd1337** [comment]
@treagod With the help of @lainsce I implemented through PR #38 the feature for your app to be into Flathub.

Now you just need to submit it. [Here](https://github.com/flathub/flathub/wiki/App-Submission) are the instructions.

Could you do it?

**Comment by btd1337** [comment]
According to @lainsce it's necessary to add this patch to enable the theme switch.

https://raw.githubusercontent.com/flathub/com.github.lainsce.notejot/master/elementary-theme.patch

**Comment by treagod** [comment]
[It's on flathub now](https://flathub.org/apps/details/com.github.treagod.spectator)
