### ISSUE TITLE
Long collections don't scroll

### ISSUE THREAD

**Issue by jdmg94** [treagod/spectator#32]
**Steps to reproduce:**

1) Create a test collection
2) add elements to the collection until the collection's content exceeds the window's height

**Expected Behaviour:**

It should show/hide a scrollbar according to the content of the collections as a whole

**Actual Result:**

The content stays fixed making new requests past the viewport's height unreachable, the only way to acknowledge the existence of this requests is to see them on the `history` tab, which may also be susceptible to the same scroll bug.

**Comment by treagod** [comment]
Thanks for reporting. This will be fixed as soon as possible. I can assure you that your suspicion, that the history view is also bugged, is not correct.

**Comment by treagod** [comment]
Fixed with e5e646b0df

**Comment by btd1337** [comment]
@treagod Tested and working properly now.

This issue can be closed now.

**Comment by treagod** [comment]
Thanks for testing
