### ISSUE TITLE
Collection Rename doesn't  work

### ISSUE THREAD

**Issue by jdmg94** [treagod/spectator#33]
**Steps to Reproduce:**

1) create a collection named `foo`
2) right-click the collection and click rename from the context menu
3) enter the name `bar` on the dialog and click ok

**Expected Behaviour:** 
The name entered on the dialog is reflected in the selected collection in the side-bar.

**Current Behaviour:**
nothing happens

**Comment by jdmg94** [comment]
as per line: https://github.com/treagod/spectator/blob/b3e424e9dca28cbf12480a04945bbeac16be3921/src/Widgets/Sidebar/Container.vala#L177

the collection update is colling method `update` on a `Models.Collection` instance, but if we check the source for the model we don't have an update method defined: https://github.com/treagod/spectator/blob/master/src/Models/Collection.vala

**Comment by treagod** [comment]
Will fix it as soon as possible. As workaround hit enter after typing the new name

**Comment by treagod** [comment]
Fixed with 021fa845

**Comment by btd1337** [comment]
@treagod Tested and working properly now.

This issue can be closed now.
