### ISSUE TITLE
Feature Request: Clone Requests

### ISSUE THREAD

**Issue by xpaulnim** [treagod/spectator#34]
In the context menu when I right click a request, in addition to Edit and Delete, it would be nice to be able to clone a request.

Many thanks for this cool app.

**Comment by treagod** [comment]
Good idea. Will implement it as soon as possible

**Comment by treagod** [comment]
Implemented with a61fa66b

**Comment by xpaulnim** [comment]
Brilliant. You're the best. Thank you @treagod
