### ISSUE TITLE
Bug: App missing screenshots on AppCenter

### ISSUE THREAD

**Issue by btd1337** [treagod/spectator#36]
![Captura de tela de 2019-10-02 21-51-44](https://user-images.githubusercontent.com/11943860/66092122-1e08ea80-e561-11e9-8d48-38fa866fc5a3.png)

**Comment by btd1337** [comment]
You need to release a new version for appcenter to update and fix this bug.

**Comment by treagod** [comment]
I know, sorry for the delay
please grant me one more week, afterwards I should have time to spend more time on this project again

**Comment by treagod** [comment]
I'm closing this as it seemes to be fine on AppCenter
