### ISSUE TITLE
Allow setting default response view [Feature request]

### ISSUE THREAD

**Issue by xpaulnim** [treagod/spectator#42]
When a response is received, the response view is set to JSON Tree. It would be nice if I could either set the default response view, or keep the currently selected response view for a request.

Thank you

**Comment by treagod** [comment]
With the latest change the response view caches which tab you have selected. Please check it out and tell me if it meets your expectations.

Sorry for the long wait

**Comment by xpaulnim** [comment]
Brilliant. Thank you for this great tool.
