### ISSUE TITLE
Change required for AppCenter: Release description

### ISSUE THREAD

**Issue by cassidyjames** [treagod/spectator#45]
Thanks for submitting your 0.4.2 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). You can include the 0.4.2 details in the next version's release description (e.g. 0.4.3) since 0.4.2 will have never reached users.

As always, if you have any questions you can reply here.

**Comment by treagod** [comment]
Thanks for the feedback.

I added a release desscription in [this commit](https://github.com/treagod/spectator/commit/bbb7702bc01ed345e030efda9ccdb29ca6b24c75).

If anything is missing feel free to respond here. If everything is fine please close this issue.

**Comment by cassidyjames** [comment]
@treagod the description itself looks great! But since releases are immutable, you'll need to mark those notes as `0.4.3`, make an 0.4.3 release here on GitHub, and then submit that to the AppCenter Dashboard.

**Comment by treagod** [comment]
Can I close this issue? 0.4.3 with the updated release notes was accepted

**Comment by cassidyjames** [comment]
Yep, good to go!
