### ISSUE TITLE
Daktape dependency on Arch

### ISSUE THREAD

**Issue by gavr123456789** [treagod/spectator#46]
Where can I get daktape dep on Arch.
I can't find it

**Comment by gavr123456789** [comment]
Whoops just typo. Great app!

**Comment by gavr123456789** [comment]
Btw works on Arch GNOME(would be cool to add gnome theme like in Drawing app) 
![image](https://user-images.githubusercontent.com/30507409/94696730-087afc00-0340-11eb-847b-e6e7305c9b67.png)

![image](https://user-images.githubusercontent.com/30507409/94696579-dec1d500-033f-11eb-9ebc-4448630c7ebb.png)

**Comment by treagod** [comment]
Thanks for the feedback :) 

I'll look into adding an option to change the the theme. But this will take a while as I am currently working on a huge refactor. Maybe leave an issue, so that I won't forget your suggestion :)
