### ISSUE TITLE
Text overflow in JSON tree view

### ISSUE THREAD

**Issue by pedro2555** [treagod/spectator#48]
Currently if the contents of a field end up beeing wider than the actual space for the widget, the text just ends up hidden. Either:

 * Wrap the text at the widget bound;
 * Add a tooltip on hover to display the full contents;
 * Both of the above.

![image](https://user-images.githubusercontent.com/1645623/95334107-99ecef80-08a5-11eb-88e3-eda80c50bd04.png)

**Comment by treagod** [comment]
Thanks for the feedback. It is already done [in the rewrite](https://github.com/treagod/spectator/pull/44) and will hopefully be released soon

**Comment by pedro2555** [comment]
Awesome. Thanks.
