### ISSUE TITLE
Use HdyWindow to give windows round corners

### ISSUE THREAD

**Issue by hanaral** [treagod/spectator#49]
It seems that all of the default elementary apps are getting it, and most of them are done already. It seems pretty trivial, I can't see where it would cause any issues.

**Comment by treagod** [comment]
Do Elementary 5 apps already use it or is it a change intended for Elementary 6?

I've already seen it, but wanted to wait till Elementary 6. Its indeed not a huge change

Thanks for the feedback anyway!

**Comment by hanaral** [comment]
> Do Elementary 5 apps already use it or is it a change intended for Elementary 6?
> 
> I've already seen it, but wanted to wait till Elementary 6. Its indeed not a huge change
> 
> Thanks for the feedback anyway!

I meant for Odin, but I thought it would be good to implement it now since you already seem to be refactoing the app in another branch

**Comment by treagod** [comment]
I created a PR (#51). You can review it if you like. Like stated, this PR will be merged when Odin is officially released.

**Comment by hanaral** [comment]
Doesn't seem to have any issues - not sure how to officially review it

**Comment by treagod** [comment]
I've integrated it into the main branch. As soon as Odin will be released I will make a new Spectator Release.

**Comment by hanaral** [comment]
If it's not done already I'll see if I can fit in creating an Odin AppCenter flatpak manifest!

**Comment by treagod** [comment]
[Here](https://github.com/flathub/com.github.treagod.spectator/blob/master/com.github.treagod.spectator.json) is already a Flatpak Manifest, which just needs to include the libhandy dependency. Right now it does not make sense to include the dependency as the Spectator Version with libhandy has no release yet. 
I'll read the reworked elementary developer docs to see if I have to do anything new

**Comment by hanaral** [comment]
For the AppCenter you need to build with the io.elementary.Sdk, which includes libhandy

**Comment by hanaral** [comment]
Created #64
