### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [treagod/spectator#73]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by treagod** [comment]
Hi,

thank you for reaching out :)

The [flatpak YAML](https://github.com/treagod/spectator/blob/main/com.github.treagod.spectator.yml) was already integrated some time ago by @hanaral. 

Just tried the flatpak version on Elementary 6 Beta, which is working just fine:
![flatpak_spectator](https://user-images.githubusercontent.com/4701538/125620163-09634077-4820-4a24-8baf-b98dbc91234e.png)

I would close this issue as it is already done. If I missed something, please let me know :)

**Comment by hanaral** [comment]
@treagod I don't think it would be inappropriate here to ask for flatpak compiling with the Sdk to become the only recommended way - I've opened  #76 to fix it

**Comment by danrabbit** [comment]
Looks great! Happy to close this issue :)

The only thing I can think to mention is that we now have a stable release of the Flatpak platform so you probably want to switch your app over from using `daily` to `6` :)

**Comment by danrabbit** [comment]
Looking through your repo, I think you just need updated screenshots and then this is good to go! I'll keep an eye on spectator for a release and get an import set up as soon as you're ready! :)
