### ISSUE TITLE
Add your stripe key to appdata

### ISSUE THREAD

**Issue by danrabbit** [treagod/spectator#75]
In the new version of AppCenter Dashboard, we're no longer modifying your appdata before publishing, so you'll need to add your stripe key to appdata.xml to continue to monetize your app in elementary OS 6

For your convenience, your public stripe key is:
`<value key="x-appcenter-stripe">pk_live_jDRKjcQ9mEOoQNMQlsSObXLA</value>`

**Comment by treagod** [comment]
Thanks for the reminder,

just one queston: where is this key from? My stripe dashboard shows me a different publishable key

**Comment by danrabbit** [comment]
Hey sorry for taking a while to reply here! Things got lost in all my notifications >.<

This key is one we generate for your app based on our stripe store. This way the key is only good for your specific app on AppCenter and can't be abused. It should be different from your public key in your stripe dashboard

**Comment by treagod** [comment]
Well then it's already done :) I added it with 9e33d4d

**Comment by danrabbit** [comment]
Great! It looks like you need to update your screenshots and then make a new release and we can get Spectator published in OS 6 :)
