### ISSUE TITLE
I made an Icon for spectator

### ISSUE THREAD

**Issue by naaando** [treagod/spectator#8]
Felling that the current icon doesn't match elementary's HIG I made an icon based on the idea behind yours but with a conspiracy theory parody for fun, I can make a pull request if this can be interesting for your project. What do you think?

128x
![image](https://user-images.githubusercontent.com/12532760/53685262-177a7200-3cf7-11e9-8f72-1188e17a0d03.png)

64x
![image](https://user-images.githubusercontent.com/12532760/53685294-6f18dd80-3cf7-11e9-871c-db6428e7e9e6.png)

**Comment by treagod** [comment]
Hi naaando,

I appreciate your effort for creating a new icon.

I admit, Spectator needs another icon. I'm no designer and need some help finding a better, more fitting icon. 

But I have to say, your icon does not fit my taste for this application, so I'm sticking with the current one for now.

**Comment by naaando** [comment]
Yeah nevermind, I made it for fun anyway. Best regards.
